
baseurl: "/LBRYians" # apply repo name if use it under gh-pages branch

    values:
defaults:
  - scope:
      type: tools
      layout: default

# Build settings
markdown    : kramdown


exclude: [ "README.md", "TODO.md", "LICENSE" ]
